

--4

SELECT 
    AA.AIRLINE_NAME,
    AFS.FLIGHTNO,
    AF.DEPARTURE
FROM 
    AIR_FLIGHTS_SCHEDULES AFS
INNER JOIN 
    AIR_AIRLINES AA ON AFS.AIRLINE_ID = AA.AIRLINE_ID
INNER JOIN 
    AIR_AIRPORTS ARR_AIRPORT ON AFS.TO_AIRPORT_ID = ARR_AIRPORT.AIRPORT_ID
INNER JOIN 
    AIR_AIRPORTS_GEO AG ON ARR_AIRPORT.AIRPORT_ID = AG.AIRPORT_ID
INNER JOIN 
    AIR_FLIGHTS AF ON AFS.FLIGHTNO = AF.FLIGHTNO
WHERE 
    AG.CITY = 'NEW YORK'
    AND (AFS.TUESDAY = 1 OR AFS.WEDNESDAY = 1 OR AFS.THURSDAY = 1)
    AND EXTRACT(MONTH FROM AF.DEPARTURE) = 3;

--5


SELECT 
    AP.FIRSTNAME, 
    AP.LASTNAME, 
    APD.CITY, 
    APD.COUNTRY, 
    AB.FLIGHT_ID, 
    AB.SEAT, 
    AB.PRICE
FROM 
    AIR_PASSENGERS AP
INNER JOIN 
    AIR_PASSENGERS_DETAILS APD ON AP.PASSENGER_ID = APD.PASSENGER_ID
INNER JOIN 
    AIR_BOOKINGS AB ON AP.PASSENGER_ID = AB.PASSENGER_ID
WHERE 
    APD.COUNTRY = 'BRAZIL' OR APD.COUNTRY = 'USA';



-- 1

SELECT 
    AP.FIRSTNAME || ' ' || AP.LASTNAME AS FullName,
    TRUNC(MONTHS_BETWEEN(SYSDATE, APD.BIRTHDATE) / 12) AS Age,
    APD.CITY
FROM 
    AIR_PASSENGERS_DETAILS APD   
INNER JOIN 
    AIR_PASSENGERS AP
    ON AP.PASSENGER_ID = APD.PASSENGER_ID
WHERE 
    APD.SEX = 'w'
    AND APD.COUNTRY = 'BRAZIL' 
    AND APD.BIRTHDATE <= ADD_MONTHS(SYSDATE,-40*12);


CREATE INDEX idx_country ON AIR_PASSENGERS_DETAILS(COUNTRY);
ANALYZE TABLE AIR_PASSENGERS_DETAILS COMPUTE STATISTICS;




CREATE CLUSTER CLUSTER_PASSENGER_ID
(PASSENGER_ID NUMBER(12))
HASHKEYS 37000            
HASH IS PASSENGER_ID SIZE 120;

DROP TABLE AIR_PASSENGERS;
CREATE TABLE AIR_PASSENGERS
CLUSTER CLUSTER_PASSENGER_ID(PASSENGER_ID)
AS SELECT * FROM DSILVA.AIR_PASSENGERS;


SELECT COUNT(*)
FROM AIR_PASSENGERS_DETAILS;

--2 

SELECT 
    AA.AIRLINE_NAME,
    AP.AIRPLANE_ID,
    AT.NAME AS AIRPLANE_TYPE_NAME,
    COUNT(AF.FLIGHT_ID) AS NUMBER_OF_FLIGHTS
FROM 
    AIR_FLIGHTS AF
INNER JOIN 
    AIR_AIRLINES AA ON AF.AIRLINE_ID = AA.AIRLINE_ID
INNER JOIN 
    AIR_AIRPLANES AP ON AF.AIRPLANE_ID = AP.AIRPLANE_ID
INNER JOIN 
    AIR_AIRPLANE_TYPES AT ON AP.AIRPLANE_TYPE_ID = AT.AIRPLANE_TYPE_ID
INNER JOIN 
    AIR_AIRPORTS FROM_A ON AF.FROM_AIRPORT_ID = FROM_A.AIRPORT_ID
INNER JOIN 
    AIR_AIRPORTS TO_A ON AF.TO_AIRPORT_ID = TO_A.AIRPORT_ID
INNER JOIN 
    AIR_AIRPORTS_GEO FROM_AG ON FROM_A.AIRPORT_ID = FROM_AG.AIRPORT_ID
INNER JOIN 
    AIR_AIRPORTS_GEO TO_AG ON TO_A.AIRPORT_ID = TO_AG.AIRPORT_ID
WHERE 
    FROM_AG.COUNTRY = 'BRAZIL' AND TO_AG.COUNTRY = 'BRAZIL'
GROUP BY 
    AA.AIRLINE_NAME, AP.AIRPLANE_ID, AT.NAME;


CREATE INDEX idx_airport_id ON AIR_AIRPORTS_GEO(COUNTRY);
ANALYZE TABLE AIR_AIRPORTS_GEO COMPUTE STATISTICS;



SELECT COUNT(*)
FROM AIR_AIRPORTS_GEO; -- 10000


CREATE CLUSTER CLUSTER_AIR_AIRPORTS_GEO
(COUNTRY VARCHAR (50))
HASHKEYS 260            
SIZE 2600;


SELECT COUNT(*)
FROM AIR_AIRPORTS;

DROP TABLE AIR_AIRPORTS_GEO;
CREATE TABLE AIR_AIRPORTS_GEO
CLUSTER CLUSTER_AIR_AIRPORTS_GEO(COUNTRY)
AS SELECT * FROM DSILVA.AIR_AIRPORTS_GEO;

SELECT avg_row_len
FROM user_tables
WHERE table_name = 'AIR_AIRPORTS';


SELECT COUNT(DISTINCT COUNTRY)
FROM AIR_AIRPORTS_GEO;


CREATE CLUSTER CLUSTER_AIR_AIRPORTS
(AIRPORT_ID NUMBER (5))
HASHKEYS 10000            
SIZE 32;

DROP TABLE AIR_AIRPORTS;
CREATE TABLE AIR_AIRPORTS
CLUSTER CLUSTER_AIR_AIRPORTS(AIRPORT_ID)
AS SELECT * FROM DSILVA.AIR_AIRPORTS;




--3

SELECT 
    AF.FLIGHTNO AS FlightNumber,
    DEP_AIRPORT.NAME AS DepartureAirport,
    ARR_AIRPORT.NAME AS ArrivalAirport,
    (AP.FIRSTNAME || ' ' || AP.LASTNAME) AS FullName,
    AB.SEAT AS SeatNumber
FROM 
    AIR_FLIGHTS AF
INNER JOIN 
    AIR_AIRPORTS DEP_AIRPORT ON AF.FROM_AIRPORT_ID = DEP_AIRPORT.AIRPORT_ID
INNER JOIN 
    AIR_AIRPORTS ARR_AIRPORT ON AF.TO_AIRPORT_ID = ARR_AIRPORT.AIRPORT_ID
INNER JOIN 
    AIR_BOOKINGS AB ON AF.FLIGHT_ID = AB.FLIGHT_ID
INNER JOIN 
    AIR_PASSENGERS AP ON AB.PASSENGER_ID = AP.PASSENGER_ID
WHERE 
    TRUNC(AF.DEPARTURE) = DATE '2023-03-25';



CREATE INDEX INDX_FLIGHT_ID ON AIR_BOOKINGS (FLIGHT_ID);
ANALYZE TABLE AIR_BOOKINGS COMPUTE STATISTICS;


SELECT COUNT(DISTINCT PASSENGER_ID)
FROM AIR_PASSENGERS; --36 095

SELECT avg_row_len
FROM user_tables
WHERE table_name = 'AIR_PASSENGERS';

CREATE CLUSTER CLUSTER_PASSENGER_ID
(PASSENGER_ID NUMERIC (12))
HASHKEYS 37000            
SIZE 32;

DROP TABLE AIR_PASSENGERS;
CREATE TABLE AIR_PASSENGERS
CLUSTER CLUSTER_PASSENGER_ID(PASSENGER_ID)
AS SELECT * FROM DSILVA.AIR_PASSENGERS;


SELECT avg_row_len
FROM user_tables
WHERE table_name = 'AIR_AIRPORTS';

SELECT COUNT(AIRPORT_ID)
FROM AIR_AIRPORTS; -- 9854

CREATE CLUSTER CLUSTER_AIRPORT_ID
(AIRPORT_ID NUMERIC (5))
HASHKEYS 10000            
SIZE 32;