
-- QUESTAO 1

CREATE INDEX idx_country ON AIR_PASSENGERS_DETAILS(COUNTRY);

CREATE CLUSTER CLUSTER_PASSENGER_ID
(PASSENGER_ID NUMBER(12))
HASHKEYS 37000            
HASH IS PASSENGER_ID SIZE 120;


-- QUESTAO 2 

CREATE INDEX idx_airport_id ON AIR_AIRPORTS_GEO(COUNTRY);

CREATE CLUSTER CLUSTER_AIR_AIRPORTS_GEO
(COUNTRY VARCHAR (50))
HASHKEYS 260            
SIZE 2600;


CREATE CLUSTER CLUSTER_AIR_AIRPORTS
(AIRPORT_ID NUMBER (5))
HASHKEYS 10000            
SIZE 32;

-- QUESTAO 3

CREATE INDEX INDX_FLIGHT_ID ON AIR_BOOKINGS (FLIGHT_ID);


CREATE CLUSTER CLUSTER_PASSENGER_ID
(PASSENGER_ID NUMERIC (12))
HASHKEYS 37000            
SIZE 32;

CREATE CLUSTER CLUSTER_AIRPORT_ID
(AIRPORT_ID NUMERIC (5))
HASHKEYS 10000            
SIZE 32;

-- QUESTAO 4

CREATE INDEX INDX_CITY ON AIR_AIRPORTS_GEO (CITY);

CREATE CLUSTER CLUSTER_AIR_AIRPORTS
(AIRPORT_ID NUMBER (5))
HASHKEYS 10000            
SIZE 32;


-- QUESTAO 5